### ISSUE TITLE
Possible job misconfiguration

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-trading-bot#12]
There are alerts indicating that the K8s job is taking more than an hour to complete (seems to happen when the pods fail):
> Job dfusion/dev-dfusion-v2-trading-bot-rinkeby-1616882400 is taking more than one hour to complete

Maybe there's an issue where some process is not completing as expected? Will look more into it Monday.

**Comment by fleupold** [comment]
I mentioned the noisy alerts to @luarx on [slack](https://gnosisinc.slack.com/archives/CQZBU9T5J/p1616766241030300?thread_ts=1616760065.028200&cid=CQZBU9T5J)

When the job fails, it's not considered as completed (even though an unretriable failure should count as a completion imo) and then these alerts show up. What I don't understand is why these alerts keep showing up even if subsequent runs of the cron job succeed (e.g. we got an "<xyz> is taking more than one hour to complete" alert today at 13:00 despite the last 12 runs succeeding without issue).

Maybe we can disable K8s monitoring system for this particular job altogether, as we are already getting alerts for stderr messages which would notify us in case the job fails, which is all we care about.

**Comment by fleupold** [comment]
Thanks to @luarx we are now no longer getting these alerts. The key was to set `failedJobsHistoryLimit: 0`
